using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Registro_de_Calificaciones_Jose_Ma._Morelos_y_Pavon.Models;
using Registro_de_Calificaciones_Jose_Ma._Morelos_y_Pavon.Services;

namespace Registro_de_Calificaciones_Jose_Ma._Morelos_y_Pavon.ViewModels;

public partial class ParcialesViewModel : ObservableObject
{
    private readonly MainViewModel _mainVm;
    private readonly ParcialJsonService _parcialJsonService;
    private readonly Dictionary<string, string> _mapaGrupos = new(StringComparer.OrdinalIgnoreCase);

    private MateriaParcial _materia = new();
    private bool _cargando;
    private string _claveMateria = string.Empty;
    private string _evaluacionActual = string.Empty;
    private string? _ultimaMatriculaSeleccionada;

    public ObservableCollection<Alumno> Alumnos => _mainVm.Alumnos;
    public ObservableCollection<ActividadParcialEditor> Actividades { get; } = new();
    // Keep ActividadParcialEditor internal to this file; expose commands with public accessibility.

    [ObservableProperty] private Alumno? _alumnoSeleccionado;
    [ObservableProperty] private string _nombreMateria = string.Empty;
    [ObservableProperty] private string _nombreEvaluacion = string.Empty;
    [ObservableProperty] private string _nombreAlumno = string.Empty;
    [ObservableProperty] private string _matriculaAlumno = string.Empty;
    [ObservableProperty] private string _grupoAlumno = string.Empty;
    [ObservableProperty] private bool _mostrarGrupo = true;
    [ObservableProperty] private decimal _sumaPorcentajes;
    [ObservableProperty] private string _sumaPorcentajesTexto = "0%";
    [ObservableProperty] private string _porcentajeEstado = "Ok";
    [ObservableProperty] private bool _sumaValida = false;
    [ObservableProperty] private string _calificacionParcialTexto = "";
    [ObservableProperty] private string _estadoValidacion = "Sin cargar";
    [ObservableProperty] private string _estadoGuardado = string.Empty;

    public ParcialesViewModel(MainViewModel mainVm)
    {
        _mainVm = mainVm ?? throw new ArgumentNullException(nameof(mainVm));
        _parcialJsonService = new ParcialJsonService();

        CargarMapaGrupos();
        _mainVm.PropertyChanged += MainVm_PropertyChanged;

        if (_mainVm.Alumnos.Any())
        {
            _ultimaMatriculaSeleccionada = _mainVm.Alumnos.First().Matricula;
            AlumnoSeleccionado = _mainVm.Alumnos.First();
        }

        CargarContextoActual();
    }

    // Commands are generated by [RelayCommand] on the methods; no manual properties here.

    [RelayCommand]
    private void AgregarActividad()
    {
        if (Actividades.Count >= 4) return;

        var nueva = new ActividadParcialEditor(() => RecalcularTodo(guardarJson: false));
        // start as inactive and empty so teacher fills it
        nueva.Activa = false;
        nueva.Nombre = string.Empty;
        nueva.Porcentaje = string.Empty;
        nueva.PuntajeMaximo = string.Empty;

        Actividades.Add(nueva);
        _materia.Actividades = Actividades.Select(a => a.ToModelo()).ToList();
        RecalcularTodo(guardarJson: false);
    }

    [RelayCommand]
    private void QuitarActividad(ActividadParcialEditor editor)
    {
        if (editor == null) return;
        if (Actividades.Contains(editor))
        {
            Actividades.Remove(editor);
            _materia.Actividades = Actividades.Select(a => a.ToModelo()).ToList();
            RecalcularTodo(guardarJson: false);
        }
    }


    public void PrepararGuardado()
    {
        RecalcularTodo(guardarJson: true);
    }

    private void MainVm_PropertyChanged(object? sender, PropertyChangedEventArgs e)
    {
        if (e.PropertyName == nameof(MainViewModel.ArchivoSeleccionado) ||
            e.PropertyName == nameof(MainViewModel.EvaluacionSeleccionada))
        {
            CargarContextoActual();
        }
    }

    partial void OnAlumnoSeleccionadoChanged(Alumno? value)
    {
        if (_cargando) return;

        _ultimaMatriculaSeleccionada = value?.Matricula;

        ActualizarDatosAlumnoSeleccionado();
        CargarCapturasDelAlumnoSeleccionado();
        RecalcularTodo(guardarJson: false);
    }

    private void CargarContextoActual()
    {
        _cargando = true;

        try
        {
            NombreMateria = _mainVm.ArchivoSeleccionado ?? string.Empty;
            NombreEvaluacion = _mainVm.EvaluacionSeleccionada ?? string.Empty;
            _evaluacionActual = NombreEvaluacion;

            MostrarGrupo = !string.Equals(NombreEvaluacion, "EXTRA", StringComparison.OrdinalIgnoreCase) &&
                           !string.Equals(NombreEvaluacion, "SEM", StringComparison.OrdinalIgnoreCase);

            // Use the actual file name (more precise) when available as the
            // key for saving parciales.json entries. Fall back to the visual
            // name if the full path is not available.
            _claveMateria = !string.IsNullOrWhiteSpace(_mainVm.ArchivoCompletoActual)
                ? ObtenerClaveMateriaDesdeNombreArchivo(_mainVm.ArchivoCompletoActual)
                : ObtenerClaveMateriaDesdeNombreVisual(_mainVm.ArchivoSeleccionado);

            if (string.IsNullOrWhiteSpace(_claveMateria) || string.IsNullOrWhiteSpace(_evaluacionActual))
            {
                LimpiarVista();
                return;
            }

            string claveMateriaEval = $"{_claveMateria}_{_evaluacionActual}";
            _materia = _parcialJsonService.ObtenerMateria(claveMateriaEval) ?? new MateriaParcial();

            NormalizarActividadesEnMateria();
            ReconstruirActividadesEnPantalla();
            RestaurarAlumnoSeleccionado();
            ActualizarDatosAlumnoSeleccionado();
            CargarCapturasDelAlumnoSeleccionado();
        }
        finally
        {
            _cargando = false;
        }

        RecalcularTodo(guardarJson: false);
    }

    private void LimpiarVista()
    {
        Actividades.Clear();
        // Always show four activity editors (may be inactive/empty)
        for (int i = 0; i < 4; i++) Actividades.Add(CreateBlankEditor());
        SumaPorcentajes = 0;
        SumaPorcentajesTexto = "0%";
        CalificacionParcialTexto = "";
        EstadoValidacion = "Sin materia cargada";
        EstadoGuardado = string.Empty;
        NombreAlumno = string.Empty;
        MatriculaAlumno = string.Empty;
        GrupoAlumno = string.Empty;
        MostrarGrupo = false;
    }

    private void RestaurarAlumnoSeleccionado()
    {
        if (!string.IsNullOrWhiteSpace(_ultimaMatriculaSeleccionada))
        {
            var alumno = Alumnos.FirstOrDefault(a => string.Equals(a.Matricula, _ultimaMatriculaSeleccionada, StringComparison.OrdinalIgnoreCase));
            if (alumno != null)
            {
                AlumnoSeleccionado = alumno;
                return;
            }
        }

        if (AlumnoSeleccionado == null && Alumnos.Any())
            AlumnoSeleccionado = Alumnos.First();
    }

    private void ActualizarDatosAlumnoSeleccionado()
    {
        if (AlumnoSeleccionado == null)
        {
            NombreAlumno = string.Empty;
            MatriculaAlumno = string.Empty;
            GrupoAlumno = string.Empty;
            return;
        }

        NombreAlumno = AlumnoSeleccionado.Nombre;
        MatriculaAlumno = AlumnoSeleccionado.Matricula;
        GrupoAlumno = ObtenerGrupoDesdeJson(AlumnoSeleccionado.Matricula) ?? AlumnoSeleccionado.Grupo;
    }

    private void CargarCapturasDelAlumnoSeleccionado()
    {
        if (AlumnoSeleccionado == null)
        {
            foreach (var actividad in Actividades) actividad.PuntajeObtenido = "";
            return;
        }

        if (_materia.Calificaciones.TryGetValue(AlumnoSeleccionado.Matricula, out var capturas))
        {
            foreach (var actividad in Actividades)
            {
                if (!string.IsNullOrWhiteSpace(actividad.Nombre) && capturas.TryGetValue(actividad.Nombre, out var valor))
                {
                    actividad.PuntajeObtenido = valor.ToString("0.##", CultureInfo.InvariantCulture);
                }
                else
                {
                    actividad.PuntajeObtenido = "";
                }
            }
            return;
        }

        foreach (var actividad in Actividades) actividad.PuntajeObtenido = "";
    }

    private void NormalizarActividadesEnMateria()
    {
        // Do not auto-populate any default activities. The teacher must
        // explicitly configure activities per CAP + parcial. If there are no
        // activities stored in the JSON for this materia, leave the list
        // empty so the UI shows nothing and the teacher can create them.
        _materia.Actividades = (_materia.Actividades ?? new List<ActividadParcial>()).Take(4).ToList();
    }

    private void ReconstruirActividadesEnPantalla()
    {
        Actividades.Clear();
        // Rebuild editors only for the activities present in the materia.
        for (int i = 0; i < _materia.Actividades.Count; i++)
        {
            var modelo = _materia.Actividades[i];
            var editor = new ActividadParcialEditor(() => RecalcularTodo(guardarJson: false));
            editor.CargarDesdeModelo(modelo);
            Actividades.Add(editor);
        }
        // Ensure there are always 4 editors shown (fill with inactive blanks)
        while (Actividades.Count < 4)
        {
            Actividades.Add(CreateBlankEditor());
        }
    }

    private ActividadParcialEditor CreateBlankEditor()
    {
        var ed = new ActividadParcialEditor(() => RecalcularTodo(guardarJson: false));
        ed.Activa = false;
        ed.Nombre = string.Empty;
        ed.Porcentaje = string.Empty;
        ed.PuntajeMaximo = string.Empty;
        ed.PuntajeObtenido = string.Empty;
        return ed;
    }

    // No default activities are created automatically. The teacher must
    // configure activities per CAP + parcial; therefore no helper that
    // returns hardcoded activities is provided.

    private void RecalcularTodo(bool guardarJson)
    {
        if (_cargando) return;

        decimal sumaPorcentajes = 0m;
        decimal acumulado = 0m;
        bool logicaCorrecta = true;

        foreach (var actividad in Actividades)
        {
            if (!actividad.Activa) continue;

            if (!double.TryParse(actividad.Porcentaje, NumberStyles.Any, CultureInfo.InvariantCulture, out double porc) || porc < 0 || porc > 100)
            {
                logicaCorrecta = false;
                continue;
            }
            sumaPorcentajes += (decimal)porc;

            if (!double.TryParse(actividad.PuntajeMaximo, NumberStyles.Any, CultureInfo.InvariantCulture, out double max) || max <= 0)
            {
                logicaCorrecta = false;
                continue;
            }

            if (string.IsNullOrWhiteSpace(actividad.PuntajeObtenido))
            {
                logicaCorrecta = false;
                continue;
            }

            if (!double.TryParse(actividad.PuntajeObtenido, NumberStyles.Any, CultureInfo.InvariantCulture, out double obt) || obt < 0 || obt > max)
            {
                logicaCorrecta = false;
                continue;
            }

            acumulado += ((decimal)obt / (decimal)max) * (decimal)porc;
        }

        SumaPorcentajes = sumaPorcentajes;
        SumaPorcentajesTexto = $"{TruncarUnDecimal(sumaPorcentajes):0.0}%";

        bool porcentajesCorrectos = Math.Abs(sumaPorcentajes - 100m) < 0.0001m;
        // Indicate whether the active percentages sum to exactly 100
        SumaValida = porcentajesCorrectos;
        // Set porcentaje estado for UI coloring: "Over" (>) , "Under" (<) , "Ok" (=)
        if (sumaPorcentajes > 100m) PorcentajeEstado = "Over";
        else if (sumaPorcentajes < 100m) PorcentajeEstado = "Under";
        else PorcentajeEstado = "Ok";


        if (!porcentajesCorrectos)
            EstadoValidacion = $"Los porcentajes activos suman {sumaPorcentajes:0.0}%. Deben dar 100%.";
        else if (!logicaCorrecta)
            EstadoValidacion = "Verifica los puntajes o campos vacíos en las actividades activas.";
        else
            EstadoValidacion = "Porcentajes y calificaciones correctos.";

        if (porcentajesCorrectos && logicaCorrecta)
        {
            decimal calificacion = TruncarUnDecimal(acumulado / 10m);
            CalificacionParcialTexto = calificacion.ToString("0.0", CultureInfo.InvariantCulture);

            if (AlumnoSeleccionado != null && !string.IsNullOrWhiteSpace(_evaluacionActual))
            {
                AlumnoSeleccionado.Calificación[_evaluacionActual] = CalificacionParcialTexto;
            }
        }
        else
        {
            CalificacionParcialTexto = "";
            if (AlumnoSeleccionado != null && !string.IsNullOrWhiteSpace(_evaluacionActual))
            {
                AlumnoSeleccionado.Calificación[_evaluacionActual] = "";
            }
        }

        if (guardarJson) GuardarEnJsonLocal();

        EstadoGuardado = guardarJson ? "Guardado correcto en JSON." : string.Empty;
    }

    private void GuardarEnJsonLocal()
    {
        if (string.IsNullOrWhiteSpace(_claveMateria) || string.IsNullOrWhiteSpace(_evaluacionActual)) return;

        _materia.Actividades = Actividades.Select(a => a.ToModelo()).ToList();

        if (AlumnoSeleccionado != null && !string.IsNullOrWhiteSpace(AlumnoSeleccionado.Matricula))
        {
            var capturas = new Dictionary<string, double>(StringComparer.OrdinalIgnoreCase);
            foreach (var actividad in Actividades)
            {
                if (actividad.Activa && !string.IsNullOrWhiteSpace(actividad.Nombre))
                {
                    if (double.TryParse(actividad.PuntajeObtenido, NumberStyles.Any, CultureInfo.InvariantCulture, out double obt))
                    {
                        capturas[actividad.Nombre.Trim()] = obt;
                    }
                    else
                    {
                        capturas[actividad.Nombre.Trim()] = 0;
                    }
                }
            }
            _materia.Calificaciones[AlumnoSeleccionado.Matricula] = capturas;
        }

        string claveMateriaEval = $"{_claveMateria}_{_evaluacionActual}";
        _parcialJsonService.GuardarMateria(claveMateriaEval, _materia);
    }

    private static string ObtenerClaveMateriaDesdeNombreVisual(string? nombreVisual)
    {
        if (string.IsNullOrWhiteSpace(nombreVisual)) return string.Empty;
        string texto = nombreVisual.Trim();
        int indexEspacio = texto.IndexOf(' ');

        if (indexEspacio <= 0) return texto.Replace(' ', '_');

        string clave = texto[..indexEspacio].Trim();
        string nombre = texto[(indexEspacio + 1)..].Trim();
        return string.IsNullOrWhiteSpace(nombre) ? clave : $"{clave}_{nombre}";
    }

    private static string ObtenerClaveMateriaDesdeNombreArchivo(string rutaCompleta)
    {
        try
        {
            var nombre = Path.GetFileNameWithoutExtension(rutaCompleta);
            if (string.IsNullOrWhiteSpace(nombre)) return string.Empty;
            // Replace spaces with underscores to keep the key consistent with
            // previous behavior.
            return nombre.Trim().Replace(' ', '_');
        }
        catch
        {
            return string.Empty;
        }
    }

    private string ObtenerGrupoDesdeJson(string matricula)
    {
        return (!string.IsNullOrWhiteSpace(matricula) && _mapaGrupos.TryGetValue(matricula.Trim(), out var grupo)) ? grupo : string.Empty;
    }

    private void CargarMapaGrupos()
    {
        _mapaGrupos.Clear();
        try
        {
            string rutaJson = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Data", "grupo.json");
            if (!File.Exists(rutaJson)) return;
            string json = File.ReadAllText(rutaJson, Encoding.UTF8);
            var datos = JsonSerializer.Deserialize<List<List<string>>>(json);
            if (datos == null) return;
            foreach (var relacion in datos.Where(r => r.Count >= 2))
            {
                string matricula = relacion[0].Trim();
                if (!_mapaGrupos.ContainsKey(matricula)) _mapaGrupos.Add(matricula, relacion[1].Trim());
            }
        }
        catch { }
    }

    private static decimal TruncarUnDecimal(decimal valor) => Math.Truncate(valor * 10m) / 10m;

    [RelayCommand] private void Inicio() { if (Alumnos.Any()) AlumnoSeleccionado = Alumnos.First(); }
    [RelayCommand] private void Anterior() { if (AlumnoSeleccionado != null && Alumnos.Any()) { int i = Alumnos.IndexOf(AlumnoSeleccionado); if (i > 0) AlumnoSeleccionado = Alumnos[i - 1]; } }
    [RelayCommand] private void Siguiente() { if (AlumnoSeleccionado != null && Alumnos.Any()) { int i = Alumnos.IndexOf(AlumnoSeleccionado); if (i >= 0 && i < Alumnos.Count - 1) AlumnoSeleccionado = Alumnos[i + 1]; } }
    [RelayCommand] private void Final() { if (Alumnos.Any()) AlumnoSeleccionado = Alumnos.Last(); }
}

public partial class ActividadParcialEditor : ObservableObject
{
    private readonly Action _notificarCambio;

    [ObservableProperty] private bool _activa;
    [ObservableProperty] private string _nombre = string.Empty;
    [ObservableProperty] private string _porcentaje = string.Empty;
    [ObservableProperty] private string _puntajeMaximo = string.Empty;
    [ObservableProperty] private string _puntajeObtenido = string.Empty;

    public ActividadParcialEditor(Action notificarCambio)
    {
        _notificarCambio = notificarCambio;
    }

    public void CargarDesdeModelo(ActividadParcial modelo)
    {
        _activa = modelo.Activa;
        _nombre = modelo.Nombre;
        _porcentaje = modelo.Porcentaje == 0 ? "" : modelo.Porcentaje.ToString(CultureInfo.InvariantCulture);
        _puntajeMaximo = modelo.PuntajeMaximo == 0 ? "" : modelo.PuntajeMaximo.ToString(CultureInfo.InvariantCulture);
        _puntajeObtenido = "";

        ActualizarVistaInmediata();
    }

    public ActividadParcial ToModelo()
    {
        double.TryParse(Porcentaje, NumberStyles.Any, CultureInfo.InvariantCulture, out double porc);
        double.TryParse(PuntajeMaximo, NumberStyles.Any, CultureInfo.InvariantCulture, out double max);
        return new ActividadParcial { Activa = Activa, Nombre = Nombre?.Trim() ?? string.Empty, Porcentaje = porc, PuntajeMaximo = max };
    }

    public string FraccionTexto
    {
        get
        {
            string obt = string.IsNullOrWhiteSpace(PuntajeObtenido) ? "" : PuntajeObtenido;
            string max = string.IsNullOrWhiteSpace(PuntajeMaximo) ? "" : PuntajeMaximo;
            if (string.IsNullOrEmpty(obt) && string.IsNullOrEmpty(max)) return "";
            return $"{obt} / {max}";
        }
    }

    public string ContribucionTexto
    {
        get
        {
            if (!Activa) return "";
            if (!double.TryParse(PuntajeMaximo, NumberStyles.Any, CultureInfo.InvariantCulture, out double max) || max <= 0) return "0.0";
            if (!double.TryParse(PuntajeObtenido, NumberStyles.Any, CultureInfo.InvariantCulture, out double obt) || obt < 0) return "0.0";
            if (!double.TryParse(Porcentaje, NumberStyles.Any, CultureInfo.InvariantCulture, out double porc)) return "0.0";

            decimal contribucion = ((decimal)obt / (decimal)max) * (decimal)porc;
            return (Math.Truncate(contribucion * 10m) / 10m).ToString("0.0", CultureInfo.InvariantCulture);
        }
    }

    partial void OnActivaChanged(bool value) => NotificarActualizacion();
    partial void OnNombreChanged(string value) => _notificarCambio?.Invoke();
    partial void OnPorcentajeChanged(string value) => NotificarActualizacion();
    partial void OnPuntajeMaximoChanged(string value) => NotificarActualizacion();
    partial void OnPuntajeObtenidoChanged(string value) => NotificarActualizacion();

    private void NotificarActualizacion()
    {
        ActualizarVistaInmediata();
        _notificarCambio?.Invoke();
    }

    private void ActualizarVistaInmediata()
    {
        OnPropertyChanged(nameof(FraccionTexto));
        OnPropertyChanged(nameof(ContribucionTexto));
    }
}